services:
  edge:
    build: ./edge
    image: three-hop-lateral-ctf-edge
    ports:
      - "127.0.0.1:8090:8080"
    networks: [edge_net]
    restart: unless-stopped

  ops:
    build: ./ops
    image: three-hop-lateral-ctf-ops
    networks: [edge_net, ops_net]
    expose: ["22"]
    restart: unless-stopped

  vault:
    build: ./vault
    image: three-hop-lateral-ctf-vault
    networks: [ops_net]
    expose: ["22"]
    restart: unless-stopped

networks:
  edge_net:
    driver: bridge
  ops_net:
    driver: bridge
